name: Release new version
description: Release python project on pypi and github

inputs:
  os:
    description: 'Operating system to report'
    default: 'ubuntu-latest'
    required: false
  programming-language:
    description: 'Programming language to report'
    default: 'Unknown'
    required: false
  language-version:
    description: 'Version of the programming language'
    default: 'Unknown'
    required: false
  notifications-channel:
    description: 'Slack channel to push notifications'
    default: 'ecosystem-ci-notifications'
    required: false
  slack-api-key:
    description: 'Bot token'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Slack Notify of failure
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # Slack channel id, channel name, or user id to post message.
        channel-id: ${{ inputs.notifications-channel }}
        # https://api.slack.com/reference/block-kit
        payload: |
          {
            "text": "GitHub Nightly has failed",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "emoji": true,
                  "text": "Nightly has failed :sadparrot:"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:* ${{ github.event.repository.name }}\n*Link:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|GH Action>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*OS:* ${{ inputs.os }}\n*${{ inputs.programming-language }} version:* ${{ inputs.language-version }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-api-key }}